# Generated by Django 6.1 on 2026-08-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('Merchart_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
