# Generated by Django 6.1 on 2026-09-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Merchart_id',
            new_name='Merchant_id',
        ),
    ]
